import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const origin='https://www.svensson.design';
const apps=JSON.parse(fs.readFileSync(path.join(root,'data/apps.json'),'utf8'));
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const write=(route,html)=>{const file=path.join(root,route,'index.html');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,html);};
const json=value=>JSON.stringify(value).replace(/</g,'\\u003c');

const guideData={
  'koka-agg-olika-konsistens':{
    title:'Koka ägg med olika konsistens – planera utan att gissa',
    description:'En praktisk guide för att samla önskemål, använda en tydlig uttagsordning och göra nästa äggkok enklare att upprepa.',
    app:'perfeggtion',
    sections:[
      ['börja-med-önskemålet','Börja med konsistensen, inte minuträkningen',`<p>När flera personer vill ha ägg från samma kastrull är den viktiga frågan först <em>hur</em> varje person vill ha sitt ägg. Ord som mjuk, krämig och fast betyder inte alltid samma sak för alla. Be därför varje person välja en enkel riktning: lösare gula, mellanläge eller fastare gula. Det ger ett språk för önskemålet innan någon försöker översätta det till en tid.</p><p>Det finns ingen enda tid som alltid blir rätt. Äggens storlek, om de kommer direkt från kylskåpet, mängden vatten, kastrullen, spisens effekt och höjden där du bor påverkar förloppet. Även kylningen efteråt kan ändra upplevelsen. Därför är det bättre att se första kokningen som ett användbart test än som ett facit.</p>`],
      ['gör-en-enkel-plan','Gör en enkel plan för en gemensam kastrull',`<p>Sortera först äggen i så få grupper som möjligt. Två grupper räcker ofta: den som vill ha en mjukare gula och den som vill ha en fastare. Bestäm sedan ordningen: vilken grupp ska upp först, och vilken ska ligga kvar längre? Skriv gärna ned ordningen eller ha den synlig i mobilen innan vattnet är varmt.</p><p>Planen ska också innehålla vad som händer efter uttaget. En person kanske vill äta direkt, en annan vill kyla ägget för att stoppa fortsatt tillagning. Håll det enkelt: en kastrull, tydliga grupper och ett nästa steg per grupp. Om dagen känns stressig är färre val bättre än många små justeringar.</p>`],
      ['använd-utfallet','Använd utfallet för nästa gång',`<p>Prata kort om resultatet medan det fortfarande är lätt att minnas. Var gulan lösare eller fastare än önskat? Var vitan som personen ville ha den? Anteckna bara sådant som kan vara relevant nästa gång, exempelvis att äggen var kalla eller att den valda kylningen kändes för lång eller kort för just den här preferensen.</p><p>Att återupprepa en lyckad rutin är mer hjälpsamt än att jaga en abstrakt perfekt tid. En favoritinställning kan vara en minnesregel för din egen kastrull och dina vanor. Perfeggtion är gjord för det arbetssättet: välj ett läge, justera när din rutin kräver det, och spara det som fungerade.</p>`],
      ['nästa-kokning','En enkel checklista till nästa kokning',`<p>Samla först vad du behöver veta: hur många ägg varje person vill ha, önskad konsistens och om äggen kommer från kylskåpet eller har stått framme. Använd samma utgångsläge för alla ägg i en grupp. Om storleken varierar mycket är det lättare att sortera dem innan du börjar.</p><ol><li><strong>Skriv upp grupperna.</strong> Till exempel två ägg med lösare gula och två med fastare. Bestäm var du lägger varje grupp när den är klar.</li><li><strong>Välj samma vattenstart i appen som i kastrullen.</strong> En timer för kall start och en timer för kokande vatten beskriver olika rutiner.</li><li><strong>Ha uttagen synliga.</strong> Med Perfeggtions batchfunktion kan varje grupp ha ett eget uttag. Följ den grupp som står på tur utan att starta om kokningen för de andra.</li><li><strong>Notera en förändring i taget.</strong> Om resultatet ska bli fastare nästa gång, ändra inte samtidigt storlek, starttemperatur och kylning. Då blir det lättare att se vad som gjorde skillnad.</li></ol><p>Det användbara resultatet är en rutin du kan upprepa: vilka ägg du använde, hur du startade och vilket utfall du gillade. Spara favoriten i appen när du hittat rätt.</p>`]
    ]
  },
  'svenskt-ordspel-utan-reklam':{
    title:'Svenskt ordspel utan reklam – så väljer du ett spel att återvända till',
    description:'En guide till vad som gör ett svenskt ordspel lugnt, tydligt och roligt att spela vidare med utan reklamavbrott.',
    app:'bokstavsbrus',
    sections:[
      ['vad-du-vill-ha','Börja med vilken spelstund du vill ha',`<p>Ett bra ordspel ska passa tillfället. Ibland vill du lösa en kort nivå på bussen, ibland vill du sjunka in i en längre serie av pussel hemma. Fundera på om du vill ha en tydlig väg framåt, fri jakt på bonusord eller ett spel som går att lägga ifrån sig utan att du tappar tråden.</p><p>Svenska ord gör också skillnad. Ett spel som faktiskt arbetar med svenska ord och ett igenkännbart språk kan kännas mer direkt än ett spel där ordlistan bara har översatts. Titta på hur spelet förklarar sin mekanik: bokstavshjul, ordbygge och minikorsord kan ge olika slags tempo även om de alla kallas ordspel.</p>`],
      ['reklamfri-upplevelse','Se efter hur spelupplevelsen finansieras',`<p>"Utan reklam" är en konkret egenskap: du slipper avbrott mellan nivåer och behöver inte planera ditt spelande runt annonser. Det är ändå klokt att läsa App Store-listningen innan du laddar ned ett spel. Där syns om det finns köp i appen, om ett konto krävs och vad utvecklaren uppger om data.</p><p>Bokstavsbrus beskrivs i App Store som gratis att spela utan reklam, konto eller tracking. Det finns ett valfritt köp i appen för tipsmynt. Det betyder att du kan avgöra själv om du vill använda den vägen; App Store visar aktuellt pris innan ett köp godkänns.</p>`],
      ['spela-i-egen-takt','Välj framsteg som fungerar i din takt',`<p>En nivåstruktur kan göra det lätt att återvända eftersom nästa steg är tydligt. Samtidigt ska den inte få dig att känna att du måste spela varje dag. Funktioner som frivilliga mål, streaks och möjlighet att spela om nivåer är bäst när de känns som val, inte krav.</p><p>App Store-beskrivningen för Bokstavsbrus lyfter 700 nivåer i fjorton kapitel, bonusord, lokal statistik och möjligheten att spela om klara nivåer. Det är en kombination som passar den som vill växla mellan att gå vidare och att stanna kvar vid ett pussel för att hitta fler ord.</p>`],
      ['gör-ett-val','Gör ett val som håller längre än första kvällen',`<p>Testa ett par nivåer utan att stressa. Känns bokstäverna läsbara? Förstår du varför ett ord godtas eller inte? Kan du pausa när du vill? Om grunden fungerar brukar resten av spelet bli enklare att bedöma. Tillgänglighetsfunktioner och möjligheten att stänga av ljud kan också vara avgörande för om spelet fungerar i din vardag.</p><p>Bokstavsbrus har stöd för VoiceOver, Dynamic Type och Reduce Motion enligt App Store-listningen. Kontrollera alltid den aktuella listningen för kompatibilitet och detaljer. Det viktigaste är att spelet ger dig en behaglig återkommande stund – inte att du spelar så mycket som möjligt.</p>`]
    ]
  }
};

function head({title,description,url,image,schema,type='website'}){return `<!doctype html><html lang="sv"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#10233f"><meta name="referrer" content="strict-origin-when-cross-origin"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="author" content="Alexander Svensson"><meta name="robots" content="index, follow"><link rel="canonical" href="${origin}${url}"><meta property="og:type" content="${type}"><meta property="og:locale" content="sv_SE"><meta property="og:site_name" content="Svensson.design"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${origin}${url}"><meta property="og:image" content="${esc(image)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${esc(image)}"><link rel="icon" href="/img/favicon.ico"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/tools.css"><link rel="stylesheet" href="/css/apps.css"><script src="/js/analytics.js" defer></script><script type="application/ld+json">${json(schema)}</script></head><body class="apps-page"><a class="skip-link" href="#main">Hoppa till innehållet</a><header class="apps-header"><div class="shell"><a class="apps-brand" href="/">Svensson<span>.design</span></a><nav class="apps-nav" aria-label="Huvudnavigation"><a href="/apps/">Appar</a><a href="/verktyg/">Verktyg</a><a href="/guider/">Guider</a></nav></div></header>`;}
const footer=`<footer class="apps-footer"><div class="shell"><p>Appar och guider av Alexander Svensson</p><a href="/apps/">Appar</a><a href="/verktyg/">Verktyg</a><a href="/guider/">Guider</a><a href="/guides/" lang="en">Work guides (English)</a><button class="footer-button" type="button" data-consent-settings>Cookieinställningar</button></div></footer></body></html>`;
const crumbs=(items)=>`<nav class="shell breadcrumbs" aria-label="Brödsmulor"><a href="/">Hem</a><span aria-hidden="true">/</span>${items}</nav>`;

for(const app of apps){
  const url=`/apps/${app.slug}/`,title=`${app.name} – ${app.tagline} | Svensson.design`;
  const schema={'@context':'https://schema.org','@graph':[
    {'@type':'SoftwareApplication','@id':origin+url+'#app',name:app.name,description:app.description,url:origin+url,image:app.screenshots[0],applicationCategory:app.slug==='perfeggtion'?'LifestyleApplication':'GameApplication',operatingSystem:app.slug==='perfeggtion'?'iOS, iPadOS, macOS, watchOS':'iOS, iPadOS',downloadUrl:app.storeUrl},
    {'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Appar',item:origin+'/apps/'},{'@type':'ListItem',position:2,name:app.name,item:origin+url}]}
  ]};
  write(url,head({title,description:app.description,url,image:app.screenshots[0],schema})+`${crumbs(`<a href="/apps/">Appar</a><span aria-hidden="true">/</span><span>${esc(app.name)}</span>`)}<main id="main"><section class="shell app-hero"><div><p class="eyebrow">${esc(app.category)}</p><h1>${esc(app.name)}</h1><p class="apps-lead">${esc(app.tagline)}. ${esc(app.description)}</p><div class="app-actions"><a class="button button-primary" href="${esc(app.storeUrl)}">Hämta på App Store ↗</a><a class="button button-secondary" href="${esc(app.guide)}">Läs guiden</a></div><ul class="app-meta"><li>${esc(app.platforms)}</li><li>${esc(app.price)}</li></ul></div><figure class="app-shot"><img src="${esc(app.screenshots[0])}" alt="App Store-skärmbild från ${esc(app.name)}" width="600" height="1300" fetchpriority="high"><figcaption>Skärmbild från den officiella App Store-listningen.</figcaption></figure></section><section class="shell app-layout"><div class="app-content"><section><h2>Det här hjälper appen med</h2><ul class="check-list">${app.benefits.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section><h2>Så kommer du igång</h2><ol class="number-list">${app.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section><section class="related-box"><h2>Fördjupa dig</h2><p>Vill du ha ett tydligare arbetssätt innan du öppnar appen? <a href="${esc(app.guide)}">Läs vår guide</a> och använd den som stöd för nästa gång.</p></section><section><h2>Vanliga frågor</h2><div class="faq-list">${app.faq.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</div></section></div><aside class="app-aside"><h2>${esc(app.name)} på App Store</h2><p>Appens pris, kompatibilitet och tillgängliga köp kan ändras. Se den officiella listningen innan du hämtar appen.</p><a class="button button-primary" href="${esc(app.storeUrl)}">Öppna App Store ↗</a><p class="guide-source">Fakta och skärmbilder på denna sida är hämtade från App Stores svenska listning den 9 september 2026.</p></aside></section></main>${footer}`);
}

const cards=apps.map(app=>`<article class="app-card"><a class="app-card-image" href="/apps/${app.slug}/" tabindex="-1" aria-hidden="true"><img src="/apps/assets/${app.slug}-icon.jpg" alt="" width="512" height="512" loading="lazy"></a><div class="app-card-copy"><p class="eyebrow">${esc(app.category)}</p><h2><a href="/apps/${app.slug}/">${esc(app.name)}</a></h2><p>${esc(app.description)}</p><div class="app-card-footer"><a href="/apps/${app.slug}/">Läs om appen →</a><small>${esc(app.price)}</small></div></div></article>`).join('');
const hubSchema={'@context':'https://schema.org','@type':'CollectionPage',name:'Appar av Alexander Svensson',description:'Svenska iPhone-, iPad-, Mac- och Apple Watch-appar för vardagsrutiner och ordspel.',url:origin+'/apps/',inLanguage:'sv',mainEntity:{'@type':'ItemList',itemListElement:apps.map((app,i)=>({'@type':'ListItem',position:i+1,name:app.name,url:origin+`/apps/${app.slug}/`}))}};
write('/apps/',head({title:'Appar av Alexander Svensson | Svensson.design',description:'Utforska Perfeggtion och Bokstavsbrus: två svenska appar med tydliga uppgifter och egna sätt att spela eller planera.',url:'/apps/',image:apps[0].screenshots[0],schema:hubSchema})+`<main id="main"><section class="shell apps-intro"><p class="eyebrow">Svenska appar</p><h1>Ägg på ditt sätt. Ord i din takt.</h1><p class="apps-lead">Perfeggtion hjälper dig att planera en äggkokning efter dina preferenser. Bokstavsbrus är ett lugnt svenskt ordspel med nivåer och minikorsord.</p></section><section class="shell app-grid" aria-label="Appar">${cards}</section></main>${footer}`);

const guideCards=Object.entries(guideData).map(([slug,guide])=>`<article class="app-card"><div class="app-card-copy"><p class="eyebrow">Praktisk guide</p><h2><a href="/guider/${slug}/">${esc(guide.title)}</a></h2><p>${esc(guide.description)}</p><div class="app-card-footer"><a href="/guider/${slug}/">Läs guiden →</a><small>${esc(apps.find(a=>a.slug===guide.app).name)}</small></div></div></article>`).join('');
const guideHubSchema={'@context':'https://schema.org','@type':'CollectionPage',name:'Svenska guider',description:'Praktiska guider om äggkokning och svenska ordspel.',url:origin+'/guider/',inLanguage:'sv'};
write('/guider/',head({title:'Svenska guider | Svensson.design',description:'Praktiska svenska guider för äggkokning och ordspel.',url:'/guider/',image:apps[0].screenshots[0],schema:guideHubSchema})+`<main id="main"><section class="shell apps-intro"><p class="eyebrow">Svenska guider</p><h1>Gör nästa vardagsstund enklare.</h1><p class="apps-lead">Läs konkreta råd om att planera ägg med olika konsistens och om att välja ett svenskt ordspel utan reklamavbrott.</p></section><section class="shell app-grid" aria-label="Guider">${guideCards}</section><section class="shell source-note"><h2>Guider för ditt arbete</h2><p>För appskärmbilder och kundöverlämning finns <a href="/guides/" lang="en">engelska guider och fria mallar</a>.</p></section></main>${footer}`);

for(const [slug,guide] of Object.entries(guideData)){
  const app=apps.find(a=>a.slug===guide.app),url=`/guider/${slug}/`,wordCount=guide.sections.map(([,title,html])=>title+' '+html.replace(/<[^>]+>/g,' ')).join(' ').trim().split(/\s+/).length;
  const schema={'@context':'https://schema.org','@graph':[{'@type':'Article','@id':origin+url+'#article',headline:guide.title,description:guide.description,url:origin+url,mainEntityOfPage:origin+url,inLanguage:'sv',image:[app.screenshots[0]],author:{'@type':'Person','@id':origin+'/#alexander',name:'Alexander Svensson',url:origin+'/'},publisher:{'@type':'Person','@id':origin+'/#alexander',name:'Alexander Svensson',url:origin+'/'},wordCount},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Guider',item:origin+'/guider/'},{'@type':'ListItem',position:2,name:guide.title,item:origin+url}]}]};
  const toc=guide.sections.map(([id,title])=>`<li><a href="#${id}">${esc(title)}</a></li>`).join('');
  const sections=guide.sections.map(([id,title,html])=>`<section id="${id}"><h2>${esc(title)}</h2>${html}</section>`).join('');
  write(url,head({title:guide.title+' | Svensson.design',description:guide.description,url,image:app.screenshots[0],schema,type:'article'})+`${crumbs(`<a href="/guider/">Guider</a><span aria-hidden="true">/</span><span>${esc(app.name)}</span>`)}<main id="main"><article class="shell"><header class="guide-hero"><p class="eyebrow">Guide · ${esc(app.name)}</p><h1>${esc(guide.title)}</h1><p class="apps-lead">${esc(guide.description)}</p></header><div class="guide-layout"><aside class="guide-toc"><nav aria-label="På sidan"><h2>På sidan</h2><ol>${toc}</ol></nav></aside><div class="guide-body">${sections}<section class="cta-row"><h2>Fortsätt med ${esc(app.name)}</h2><p>${esc(app.description)}</p><a class="button button-secondary" href="/apps/${app.slug}/">Läs om ${esc(app.name)}</a></section><section class="source-note"><h2>Om guiden</h2><p>Jag utvecklar ${esc(app.name)}. Funktionsuppgifter om ${esc(app.name)} kommer från <a href="${esc(app.storeUrl)}">den svenska App Store-listningen</a>, kontrollerad 9 september 2026.</p></section></div></div></article></main>${footer}`);
}
console.log(`Generated ${apps.length} app pages, an app hub and ${Object.keys(guideData).length} Swedish guides.`);
