import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const products = JSON.parse(fs.readFileSync(path.join(root, 'data/tools.json'), 'utf8'));
const origin = 'https://www.svensson.design';
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const route = (lang, slug = '') => `/${lang === 'sv' ? 'verktyg' : 'tools'}/${slug ? slug + '/' : ''}`;
const write = (url, html) => { const file = path.join(root, url, 'index.html'); fs.mkdirSync(path.dirname(file), {recursive:true}); fs.writeFileSync(file, html); };
const text = {
 sv:{all:'Alla verktyg',about:'Om Alexander',lang:'English',other:'en',buy:'Köp på Gumroad',once:'Engångsköp',tax:'Priser i USD. Slutpris och eventuell skatt visas på Gumroad.',demo:'Prova gratis demo',learn:'Läs om verktyget',who:'Vem passar det för?',benefits:'Det här hjälper verktyget dig med',steps:'Så fungerar det',included:'Det här ingår',limits:'Bra att veta före köp',faq:'Vanliga frågor',related:'Fler verktyg för ditt arbete',compat:'Testat på Mac i Chrome och Safari',purchase:'Köp och leverans',purchaseBody:'Köpet och nedladdningen hanteras av Gumroad under butiksnamnet Voxlessa. Läs fullständig licens, supportinformation och villkor på produktsidan innan du köper.',refund:'30 dagars pengarna tillbaka-garanti enligt villkoren på Gumroad.',privacy:'Fungerar offline. Inget konto i verktyget.',preview:'Verklig produktvy med fiktivt exempel.',example:'Färdiga exporter från det medföljande fiktiva exemplet.',demoText:'Prova ett exempel med en bild, ett språk och ett iPhone-format direkt i webbläsaren. Dina filer behandlas i din webbläsare. Fullversionen köps separat.',sample:'Ladda ned exempel på färdiga exporter',watch:'Se den korta genomgången',home:'Hem',overviewTitle:'Offlineverktyg för Mac – skärmbilder, offerter och kreativt arbete',overviewDescription:'Sex fristående verktyg för skärmbilder, offerter, kampanjbilder, kundöverlämning, OBS och undertexter. Engångsköp via Gumroad. Prova ShotLattice gratis.',headline:'Små verktyg. Färdigt arbete.',intro:'Förbered nästa appsläpp, bygg en tydlig offert eller lämna över en webbplats. Sex verktyg som arbetar med dina filer lokalt på din Mac.',eyebrow:'Verktyg av Alexander Svensson',featured:'För nästa appsläpp',catalog:'Hitta verktyget för ditt nästa steg',demoLimit:'Gratis demo · 1 bild · 1 språk · 1 format',footer:'Byggt av Alexander Svensson · Säljs som Voxlessa på Gumroad'},
 en:{all:'All tools',about:'About Alexander',lang:'Svenska',other:'sv',buy:'Buy on Gumroad',once:'One-time purchase',tax:'Prices in USD. Final price and any tax are shown on Gumroad.',demo:'Try the free demo',learn:'Explore the tool',who:'Who is it for?',benefits:'What you can do',steps:'How it works',included:'What is included',limits:'Before you buy',faq:'Frequently asked questions',related:'More tools for your work',compat:'Tested on Mac in Chrome and Safari',purchase:'Purchase and delivery',purchaseBody:'Gumroad handles checkout and downloads under the store name Voxlessa. Read the full license, support information and terms on the product page before purchasing.',refund:'30-day money-back guarantee under the terms on Gumroad.',privacy:'Works offline. No account in the tool.',preview:'Actual product view with a fictional example.',example:'Actual exports from the included fictional example.',demoText:'Try one example image, one language and one iPhone format in your browser. Your files are processed in your browser. The full version is sold separately.',sample:'Download sample screenshot exports',watch:'Watch the short walkthrough',home:'Home',overviewTitle:'Offline Mac tools for app screenshots, quotes and creative work',overviewDescription:'Six local tools for app screenshots, quotes, campaign images, website handovers, OBS overlays and subtitles. Buy once on Gumroad. Try ShotLattice free.',headline:'Small tools. Finished work.',intro:'Prepare an app release, build a clear quote or hand over a website. Six focused tools that work with your files locally on your Mac.',eyebrow:'Tools by Alexander Svensson',featured:'For your next app release',catalog:'Find the tool for your next step',demoLimit:'Free demo · 1 image · 1 language · 1 format',footer:'Built by Alexander Svensson · Sold as Voxlessa on Gumroad'}
};

function buyLink(p, lang, position='page') {
 const url=new URL(p.gumroadUrl);
 url.search=new URLSearchParams({utm_source:'svensson.design',utm_medium:'website',utm_campaign:'tools_launch_2026_09',utm_content:`${p.slug}_${lang}_${position}`});
 return esc(url.href);
}
function head(lang, title, description, url, image, schema) {
 const alternate=url.replace(lang==='sv'?'/verktyg/':'/tools/',lang==='sv'?'/tools/':'/verktyg/');
 return `<!doctype html>\n<html lang="${lang}"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#10233f"><meta name="referrer" content="strict-origin-when-cross-origin">
<title>${esc(title)}</title><meta name="description" content="${esc(description)}">
<meta name="robots" content="index, follow"><link rel="canonical" href="${origin}${url}">
<link rel="alternate" hreflang="${lang}" href="${origin}${url}"><link rel="alternate" hreflang="${text[lang].other}" href="${origin}${alternate}"><link rel="alternate" hreflang="x-default" href="${origin}${lang==='en'?url:alternate}">
<meta property="og:type" content="website"><meta property="og:locale" content="${lang==='sv'?'sv_SE':'en_US'}"><meta property="og:site_name" content="Svensson.design">
<meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${origin}${url}"><meta property="og:image" content="${origin}${image}">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${origin}${image}">
<link rel="icon" href="/img/favicon.ico"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/tools.css">
<script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script>
</head><body class="tools-page"><a class="skip-link" href="#main">${lang==='sv'?'Hoppa till innehållet':'Skip to content'}</a>
<header class="tools-header"><div class="shell"><a class="tools-brand" href="/">Svensson<span>.design</span></a><nav aria-label="${lang==='sv'?'Huvudnavigation':'Main navigation'}"><a href="${route(lang)}">${text[lang].all}</a><a href="/#contact">${text[lang].about}</a><a class="language-link" href="${alternate}" lang="${text[lang].other}" hreflang="${text[lang].other}">${text[lang].lang}</a></nav></div></header>`;
}
const foot = lang => `<footer class="tools-footer"><div class="shell"><p>${text[lang].footer}</p><a href="${route(lang)}">${text[lang].all}</a><a href="/">Svensson.design</a></div></footer></body></html>\n`;
function artwork(p, lang, priority=false) {
 if(p.slug==='shotlattice') return `<figure class="shot-art"><div class="export-strip">${['headline','side','subtitle'].map((layout,i)=>`<img src="/tools/assets/shotlattice-export-${layout}.png" alt="${lang==='sv'?'Exempel på exporterad skärmbild':'Exported screenshot example'}: ${layout}" width="1320" height="2868" ${priority&&i===0?'fetchpriority="high"':'loading="lazy"'} decoding="async">`).join('')}</div><figcaption>${text[lang].example}</figcaption></figure>`;
 return `<figure class="product-art"><img src="/tools/assets/${p.slug}-preview.webp" alt="${esc(p.name)} – ${text[lang].preview}" width="1440" height="1050" ${priority?'fetchpriority="high"':'loading="lazy"'} decoding="async"><figcaption>${text[lang].preview}</figcaption></figure>`;
}
function card(p, lang){const c=p[lang];return `<article class="tool-card"><a class="card-image" href="${route(lang,p.slug)}" tabindex="-1" aria-hidden="true"><img src="/tools/assets/${p.slug}-preview.webp" alt="" width="1440" height="1050" loading="lazy" decoding="async"></a><div class="card-copy"><p class="eyebrow">${esc(p.name)}</p><h3><a href="${route(lang,p.slug)}">${esc(c.headline)}</a></h3><p>${esc(c.intro)}</p><div class="card-bottom"><a class="text-link" href="${route(lang,p.slug)}">${text[lang].learn}<span class="visually-hidden">: ${esc(p.name)}</span> →</a><span>$${p.price} <small>USD</small></span></div></div></article>`;}

for(const lang of ['sv','en']){
 const t=text[lang],p=products[0],c=p[lang],url=route(lang);
 const schema={'@context':'https://schema.org','@type':'CollectionPage',name:t.overviewTitle,description:t.overviewDescription,url:origin+url,inLanguage:lang,mainEntity:{'@type':'ItemList',itemListElement:products.map((p,i)=>({'@type':'ListItem',position:i+1,name:p.name,url:origin+route(lang,p.slug)}))}};
 write(url,head(lang,t.overviewTitle,t.overviewDescription,url,'/tools/assets/shotlattice-cover.png',schema)+`
<main id="main"><section class="tools-intro shell"><p class="eyebrow">${t.eyebrow}</p><h1>${t.headline}</h1><p class="tools-lead">${t.intro}</p><ul class="trust-row"><li>${t.once}</li><li>${t.privacy}</li><li>${t.compat}</li></ul></section>
<section class="shell featured-tool" aria-labelledby="featured-title"><div><p class="eyebrow">${t.featured} · ${p.name}</p><h2 id="featured-title">${esc(c.headline)}</h2><p>${esc(c.intro)}</p><div class="tool-actions"><a class="button button-primary" href="${route(lang,p.slug)}">${t.learn}</a><a class="button button-secondary" href="/tools/shotlattice/demo/">${t.demo}</a></div><p class="subtle">${t.demoLimit}</p></div>${artwork(p,lang,true)}</section>
<section class="shell tool-catalog" aria-labelledby="catalog-title"><h2 id="catalog-title">${t.catalog}</h2><div class="tools-grid">${products.map(p=>card(p,lang)).join('')}</div><p class="subtle">${t.tax}</p></section></main>`+foot(lang));
 for(const p of products){const c=p[lang],url=route(lang,p.slug),image=p.slug==='shotlattice'?'/tools/assets/shotlattice-cover.png':`/tools/assets/${p.slug}-preview.webp`;
 const app={'@type':'SoftwareApplication','@id':origin+url+'#software',name:p.name,description:c.description,url:origin+url,image:origin+image,operatingSystem:'macOS',applicationCategory:'UtilitiesApplication',offers:{'@type':'Offer',price:String(p.price),priceCurrency:'USD',url:p.gumroadUrl}};
 const schema={'@context':'https://schema.org','@graph':[app,{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:t.all,item:origin+route(lang)},{'@type':'ListItem',position:2,name:p.name,item:origin+url}]}]};
 const related=products.filter(x=>x.slug!==p.slug).slice(0,3);
 write(url,head(lang,c.title,c.description,url,image,schema)+`
<main id="main"><div class="shell breadcrumbs"><a href="${route(lang)}">${t.all}</a><span aria-hidden="true">/</span><span>${esc(p.name)}</span></div>
<section class="shell product-hero"><div><p class="eyebrow">${esc(p.name)} · ${t.once}</p><h1>${esc(c.headline)}</h1><p class="tools-lead">${esc(c.intro)}</p><p class="product-price">$${p.price} <span>USD · ${t.once.toLowerCase()}</span></p><div class="tool-actions"><a class="button button-primary" href="${buyLink(p,lang,'hero')}">${t.buy} ↗</a>${p.slug==='shotlattice'?`<a class="button button-secondary" href="/tools/shotlattice/demo/">${t.demo}</a>`:''}</div><p class="purchase-note">${t.tax}</p><p class="subtle">${t.compat}<br>${t.privacy}</p></div>${artwork(p,lang,true)}</section>
<section class="shell product-detail"><div class="detail-copy"><section><p class="eyebrow">${t.who}</p><p class="audience">${esc(c.audience)}</p></section><section><h2>${t.benefits}</h2><ul class="benefit-list">${c.benefits.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section><h2>${t.steps}</h2><ol class="step-list">${c.steps.map((x,i)=>`<li><span aria-hidden="true">0${i+1}</span><p>${esc(x)}</p></li>`).join('')}</ol></section>
${p.slug==='shotlattice'?`<section class="demo-section"><h2>${t.demo}</h2><p>${t.demoText}</p><a class="button button-primary" href="/tools/shotlattice/demo/">${t.demo} →</a><p><a href="/tools/assets/shotlattice-sample-exports.zip" download>${t.sample} (.zip)</a></p><h3>${t.watch}</h3><video controls preload="none" poster="/tools/assets/shotlattice-cover.png" width="1280" height="720"><source src="/tools/assets/shotlattice-walkthrough.mp4" type="video/mp4"><track kind="captions" src="/tools/assets/shotlattice-walkthrough-${lang}.vtt" srclang="${lang}" label="${lang==='sv'?'Svenska':'English'}" default></video><p class="subtle">${lang==='sv'?'Stegvis genomgång med verkliga bilder från den begränsade demon.':'Step-by-step walkthrough using actual captures of the limited demo.'}</p></section>`:''}
<section><h2>${t.faq}</h2><div class="faq-list">${c.faq.map(f=>`<details><summary>${esc(f.q)}</summary><p>${esc(f.a)}</p></details>`).join('')}</div></section></div>
<aside class="purchase-panel"><h2>${t.included}</h2><ul>${c.included.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>${t.limits}</h2><ul>${c.limits.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>${t.purchase}</h2><p>${t.purchaseBody}</p><p>${t.refund}</p><a class="button button-primary" href="${buyLink(p,lang,'details')}">${t.buy} · $${p.price}</a></aside></section>
<section class="shell tool-catalog"><h2>${t.related}</h2><div class="tools-grid">${related.map(p=>card(p,lang)).join('')}</div></section></main>`+foot(lang));
 }
}
const urls=['/',...['sv','en'].flatMap(lang=>[route(lang),...products.map(p=>route(lang,p.slug))])];
fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(url=>`  <url><loc>${origin}${url}</loc><lastmod>2026-09-07</lastmod></url>`).join('\n')}\n</urlset>\n`);
console.log(`Generated ${urls.length-1} static marketing pages and sitemap.`);
